{
    "type": "error",
    "data": "Error running pipeline!",
    "stack": "Traceback (most recent call last):\n  File \"/Users/talbertherndon/Desktop/Projects/talbot/rag/venv/lib/python3.11/site-packages/graphrag/index/run/run_workflows.py\", line 166, in _run_workflows\n    result = await run_workflow(\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/talbertherndon/Desktop/Projects/talbot/rag/venv/lib/python3.11/site-packages/graphrag/index/workflows/extract_graph.py\", line 66, in run_workflow\n    graph = create_graph(base_relationship_edges)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/talbertherndon/Desktop/Projects/talbot/rag/venv/lib/python3.11/site-packages/graphrag/index/operations/create_graph.py\", line 15, in create_graph\n    metadata_df = pd.read_parquet(metadata_file)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/talbertherndon/Desktop/Projects/talbot/rag/venv/lib/python3.11/site-packages/pandas/io/parquet.py\", line 667, in read_parquet\n    return impl.read(\n           ^^^^^^^^^^\n  File \"/Users/talbertherndon/Desktop/Projects/talbot/rag/venv/lib/python3.11/site-packages/pandas/io/parquet.py\", line 267, in read\n    path_or_handle, handles, filesystem = _get_path_or_handle(\n                                          ^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/talbertherndon/Desktop/Projects/talbot/rag/venv/lib/python3.11/site-packages/pandas/io/parquet.py\", line 140, in _get_path_or_handle\n    handles = get_handle(\n              ^^^^^^^^^^^\n  File \"/Users/talbertherndon/Desktop/Projects/talbot/rag/venv/lib/python3.11/site-packages/pandas/io/common.py\", line 882, in get_handle\n    handle = open(handle, ioargs.mode)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: './ragtest/output/input.parquet'\n",
    "source": "[Errno 2] No such file or directory: './ragtest/output/input.parquet'",
    "details": null
}
{
    "type": "error",
    "data": "Error running pipeline!",
    "stack": "Traceback (most recent call last):\n  File \"/Users/talbertherndon/Desktop/Projects/talbot/rag/venv/lib/python3.11/site-packages/graphrag/index/run/run_workflows.py\", line 166, in _run_workflows\n    result = await run_workflow(\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/talbertherndon/Desktop/Projects/talbot/rag/venv/lib/python3.11/site-packages/graphrag/index/workflows/extract_graph.py\", line 66, in run_workflow\n    graph = create_graph(base_relationship_edges)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/talbertherndon/Desktop/Projects/talbot/rag/venv/lib/python3.11/site-packages/graphrag/index/operations/create_graph.py\", line 15, in create_graph\n    metadata_df = pd.read_parquet(metadata_file)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/talbertherndon/Desktop/Projects/talbot/rag/venv/lib/python3.11/site-packages/pandas/io/parquet.py\", line 667, in read_parquet\n    return impl.read(\n           ^^^^^^^^^^\n  File \"/Users/talbertherndon/Desktop/Projects/talbot/rag/venv/lib/python3.11/site-packages/pandas/io/parquet.py\", line 267, in read\n    path_or_handle, handles, filesystem = _get_path_or_handle(\n                                          ^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/talbertherndon/Desktop/Projects/talbot/rag/venv/lib/python3.11/site-packages/pandas/io/parquet.py\", line 140, in _get_path_or_handle\n    handles = get_handle(\n              ^^^^^^^^^^^\n  File \"/Users/talbertherndon/Desktop/Projects/talbot/rag/venv/lib/python3.11/site-packages/pandas/io/common.py\", line 882, in get_handle\n    handle = open(handle, ioargs.mode)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: './ragtest/output/input.parquet'\n",
    "source": "[Errno 2] No such file or directory: './ragtest/output/input.parquet'",
    "details": null
}
